/**
 * 形象槽位清单 —— 由 scripts/sync-figure-slots.mjs 从 @dicebear/* 的 schema 生成。
 *
 * **请勿手改**：改了会被 check:figure-slots-sync 门禁拦住。
 * 升级任何 @dicebear/* 之后重跑 pnpm sync:figure-slots。
 *
 * ## 读这份产物之前要知道的三件事
 *
 * 1. **变体名不是统一格式**，也不是我们能改的。实测含语义化命名
 *    （notionists.hair 的最后一个是 "hat"、lorelei.mouth 是 happy01…sad09、
 *    micah.hair 是 fonze/mrT/dougFunny）与上游拼写错误
 *    （micah.nose 的 "tound" 应为 round）。**照抄，不许修** ——
 *    改了就与 schema 不符，那个变体会变成非法值并被 DiceBear 静默忽略。
 *    UI 因此**不把变体名当可见文案**，只显缩略图 + 序号。
 *
 * 2. **变体顺序是上游的展示顺序**（notionists / lorelei 的 hair 是倒序的），
 *    不要重排。
 *
 * 3. `optional: true` 的槽位靠 `probabilityKey` 控制有无。
 *    选中一件时必须**同时**写 `probability: 100` —— 那四个概率槽的
 *    schema 默认值是 10/75/10/20（不是 0 或 100），只写变体不写概率时
 *    "这件到底出不出现"仍然由 seed 掷骰子决定。详见 figure-model.ts。
 *
 * 跳过的非枚举属性（取值区间的上下界，非枚举，UI 无从表达）：
 * thumbs.faceOffsetX thumbs.faceOffsetY thumbs.faceRotation thumbs.shapeOffsetX thumbs.shapeOffsetY thumbs.shapeRotation
 *
 * 过滤掉的单变体无开关槽位：notionists.base micah.base thumbs.shape
 * （判据是"单变体**且**无概率槽"—— lorelei.freckles / hairAccessories
 *  也是单变体，但它们有概率槽，是真开关，故保留并标 toggleOnly）
 */

/** 一个可选择的槽位（头发 / 眼睛 / 眼镜…）。 */
export interface FigureSlot {
  /** schema 里的属性名，同时是 i18n key 的尾段 */
  readonly key: string
  /** 变体名，**上游原序** */
  readonly variants: readonly string[]
  /** 有对应的 `<key>Probability` → 可以"不要" */
  readonly optional: boolean
  readonly probabilityKey?: string
  /** 单变体 + 可选 = 有/无开关，UI 渲染成 switch 而不是一格网格 */
  readonly toggleOnly?: boolean
}

export interface FigureStyleSlots {
  readonly slots: readonly FigureSlot[]
  /** 风格级颜色槽（6 位 hex 或 transparent）。notionists 实测为空 */
  readonly colorSlots: readonly string[]
}

export const FIGURE_SLOTS = {
  notionists: {
    slots: [
      {
        key: "beard",
        variants: [
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: true,
        probabilityKey: "beardProbability",
      },
      {
        key: "body",
        variants: [
          "variant25",
          "variant24",
          "variant23",
          "variant22",
          "variant21",
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "bodyIcon",
        variants: ["electric", "saturn", "galaxy"],
        optional: true,
        probabilityKey: "bodyIconProbability",
      },
      {
        key: "brows",
        variants: [
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "eyes",
        variants: ["variant05", "variant04", "variant03", "variant02", "variant01"],
        optional: false,
      },
      {
        key: "gesture",
        variants: [
          "wavePointLongArms",
          "waveOkLongArms",
          "waveLongArms",
          "waveLongArm",
          "pointLongArm",
          "okLongArm",
          "point",
          "ok",
          "hand",
          "handPhone",
        ],
        optional: true,
        probabilityKey: "gestureProbability",
      },
      {
        key: "glasses",
        variants: [
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: true,
        probabilityKey: "glassesProbability",
      },
      {
        key: "hair",
        variants: [
          "variant63",
          "variant62",
          "variant61",
          "variant60",
          "variant59",
          "variant58",
          "variant57",
          "variant56",
          "variant55",
          "variant54",
          "variant53",
          "variant52",
          "variant51",
          "variant50",
          "variant49",
          "variant48",
          "variant47",
          "variant46",
          "variant45",
          "variant44",
          "variant43",
          "variant42",
          "variant41",
          "variant40",
          "variant39",
          "variant38",
          "variant37",
          "variant36",
          "variant35",
          "variant34",
          "variant33",
          "variant32",
          "variant31",
          "variant30",
          "variant29",
          "variant28",
          "variant27",
          "variant26",
          "variant25",
          "variant24",
          "variant23",
          "variant22",
          "variant21",
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
          "hat",
        ],
        optional: false,
      },
      {
        key: "lips",
        variants: [
          "variant30",
          "variant29",
          "variant28",
          "variant27",
          "variant26",
          "variant25",
          "variant24",
          "variant23",
          "variant22",
          "variant21",
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "nose",
        variants: [
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
    ],
    colorSlots: [],
  },
  lorelei: {
    slots: [
      {
        key: "beard",
        variants: ["variant01", "variant02"],
        optional: true,
        probabilityKey: "beardProbability",
      },
      {
        key: "earrings",
        variants: ["variant01", "variant02", "variant03"],
        optional: true,
        probabilityKey: "earringsProbability",
      },
      {
        key: "eyebrows",
        variants: [
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "eyes",
        variants: [
          "variant24",
          "variant23",
          "variant22",
          "variant21",
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "freckles",
        variants: ["variant01"],
        optional: true,
        probabilityKey: "frecklesProbability",
        toggleOnly: true,
      },
      {
        key: "glasses",
        variants: ["variant01", "variant02", "variant03", "variant04", "variant05"],
        optional: true,
        probabilityKey: "glassesProbability",
      },
      {
        key: "hair",
        variants: [
          "variant48",
          "variant47",
          "variant46",
          "variant45",
          "variant44",
          "variant43",
          "variant42",
          "variant41",
          "variant40",
          "variant39",
          "variant38",
          "variant37",
          "variant36",
          "variant35",
          "variant34",
          "variant33",
          "variant32",
          "variant31",
          "variant30",
          "variant29",
          "variant28",
          "variant27",
          "variant26",
          "variant25",
          "variant24",
          "variant23",
          "variant22",
          "variant21",
          "variant20",
          "variant19",
          "variant18",
          "variant17",
          "variant16",
          "variant15",
          "variant14",
          "variant13",
          "variant12",
          "variant11",
          "variant10",
          "variant09",
          "variant08",
          "variant07",
          "variant06",
          "variant05",
          "variant04",
          "variant03",
          "variant02",
          "variant01",
        ],
        optional: false,
      },
      {
        key: "hairAccessories",
        variants: ["flowers"],
        optional: true,
        probabilityKey: "hairAccessoriesProbability",
        toggleOnly: true,
      },
      {
        key: "head",
        variants: ["variant04", "variant03", "variant02", "variant01"],
        optional: false,
      },
      {
        key: "mouth",
        variants: [
          "happy01",
          "happy02",
          "happy03",
          "happy04",
          "happy05",
          "happy06",
          "happy07",
          "happy08",
          "happy18",
          "happy09",
          "happy10",
          "happy11",
          "happy12",
          "happy13",
          "happy14",
          "happy17",
          "happy15",
          "happy16",
          "sad01",
          "sad02",
          "sad03",
          "sad04",
          "sad05",
          "sad06",
          "sad07",
          "sad08",
          "sad09",
        ],
        optional: false,
      },
      {
        key: "nose",
        variants: ["variant01", "variant02", "variant03", "variant04", "variant05", "variant06"],
        optional: false,
      },
    ],
    colorSlots: [
      "earringsColor",
      "eyebrowsColor",
      "eyesColor",
      "frecklesColor",
      "glassesColor",
      "hairAccessoriesColor",
      "hairColor",
      "mouthColor",
      "noseColor",
      "skinColor",
    ],
  },
  micah: {
    slots: [
      {
        key: "earrings",
        variants: ["hoop", "stud"],
        optional: true,
        probabilityKey: "earringsProbability",
      },
      { key: "ears", variants: ["attached", "detached"], optional: false },
      {
        key: "eyebrows",
        variants: ["up", "down", "eyelashesUp", "eyelashesDown"],
        optional: false,
      },
      {
        key: "eyes",
        variants: ["eyes", "round", "eyesShadow", "smiling", "smilingShadow"],
        optional: false,
      },
      {
        key: "facialHair",
        variants: ["beard", "scruff"],
        optional: true,
        probabilityKey: "facialHairProbability",
      },
      {
        key: "glasses",
        variants: ["round", "square"],
        optional: true,
        probabilityKey: "glassesProbability",
      },
      {
        key: "hair",
        variants: [
          "fonze",
          "mrT",
          "dougFunny",
          "mrClean",
          "dannyPhantom",
          "full",
          "turban",
          "pixie",
        ],
        optional: true,
        probabilityKey: "hairProbability",
      },
      {
        key: "mouth",
        variants: ["surprised", "laughing", "nervous", "smile", "sad", "pucker", "frown", "smirk"],
        optional: false,
      },
      { key: "nose", variants: ["curve", "pointed", "tound"], optional: false },
      { key: "shirt", variants: ["open", "crew", "collared"], optional: false },
    ],
    colorSlots: [
      "baseColor",
      "earringColor",
      "eyeShadowColor",
      "eyebrowsColor",
      "eyesColor",
      "facialHairColor",
      "glassesColor",
      "hairColor",
      "mouthColor",
      "shirtColor",
    ],
  },
  funEmoji: {
    slots: [
      {
        key: "eyes",
        variants: [
          "sad",
          "tearDrop",
          "pissed",
          "cute",
          "wink",
          "wink2",
          "plain",
          "glasses",
          "closed",
          "love",
          "stars",
          "shades",
          "closed2",
          "crying",
          "sleepClose",
        ],
        optional: false,
      },
      {
        key: "mouth",
        variants: [
          "plain",
          "lilSmile",
          "sad",
          "shy",
          "cute",
          "wideSmile",
          "shout",
          "smileTeeth",
          "smileLol",
          "pissed",
          "drip",
          "tongueOut",
          "kissHeart",
          "sick",
          "faceMask",
        ],
        optional: false,
      },
    ],
    colorSlots: ["backgroundColor"],
  },
  bottts: {
    slots: [
      {
        key: "eyes",
        variants: [
          "bulging",
          "dizzy",
          "eva",
          "frame1",
          "frame2",
          "glow",
          "happy",
          "hearts",
          "robocop",
          "round",
          "roundFrame01",
          "roundFrame02",
          "sensor",
          "shade01",
        ],
        optional: false,
      },
      {
        key: "face",
        variants: ["round01", "round02", "square01", "square02", "square03", "square04"],
        optional: false,
      },
      {
        key: "mouth",
        variants: [
          "bite",
          "diagram",
          "grill01",
          "grill02",
          "grill03",
          "smile01",
          "smile02",
          "square01",
          "square02",
        ],
        optional: true,
        probabilityKey: "mouthProbability",
      },
      {
        key: "sides",
        variants: [
          "antenna01",
          "antenna02",
          "cables01",
          "cables02",
          "round",
          "square",
          "squareAssymetric",
        ],
        optional: true,
        probabilityKey: "sidesProbability",
      },
      {
        key: "texture",
        variants: [
          "camo01",
          "camo02",
          "circuits",
          "dirty01",
          "dirty02",
          "dots",
          "grunge01",
          "grunge02",
        ],
        optional: true,
        probabilityKey: "textureProbability",
      },
      {
        key: "top",
        variants: [
          "antenna",
          "antennaCrooked",
          "bulb01",
          "glowingBulb01",
          "glowingBulb02",
          "horns",
          "lights",
          "pyramid",
          "radar",
        ],
        optional: true,
        probabilityKey: "topProbability",
      },
    ],
    colorSlots: ["baseColor"],
  },
  thumbs: {
    slots: [
      {
        key: "eyes",
        variants: [
          "variant1W10",
          "variant1W12",
          "variant1W14",
          "variant1W16",
          "variant2W10",
          "variant2W12",
          "variant2W14",
          "variant2W16",
          "variant3W10",
          "variant3W12",
          "variant3W14",
          "variant3W16",
          "variant4W10",
          "variant4W12",
          "variant4W14",
          "variant4W16",
          "variant5W10",
          "variant5W12",
          "variant5W14",
          "variant5W16",
          "variant6W10",
          "variant6W12",
          "variant6W14",
          "variant6W16",
          "variant7W10",
          "variant7W12",
          "variant7W14",
          "variant7W16",
          "variant8W10",
          "variant8W12",
          "variant8W14",
          "variant8W16",
          "variant9W10",
          "variant9W12",
          "variant9W14",
          "variant9W16",
        ],
        optional: false,
      },
      {
        key: "face",
        variants: ["variant1", "variant2", "variant3", "variant5", "variant4"],
        optional: false,
      },
      {
        key: "mouth",
        variants: ["variant2", "variant1", "variant3", "variant4", "variant5"],
        optional: false,
      },
    ],
    colorSlots: ["backgroundColor", "eyesColor", "mouthColor", "shapeColor"],
  },
} as const satisfies Record<string, FigureStyleSlots>
